config/routes.rb
Rails.application.routes.draw do


  get 'home/index'

  get '/christi' => 'home#christi'

resources :users
resources :posts
resources :sessions, except: [:destroy]
delete '/sessions' => 'sessions#destroy', as: :logout
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root 'home#index'

end  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
has_many :posts
	def full_name
		first_name + ' ' + last_name	
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :user_signed_in_?, :authenticate

  def authenticate
  	if !session[:user_id]
  	redirect_to new_session_path
  	end
  end

def current_user
	if session[:user_id]
		User.find(session[:user_id])
	end
end

def user_signed_in_?
	!session[:user_id].nil?
end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	 if user_signed_in_?
  	 	#  	opt 1 redirect_to current_user
  	 	@user = current_user 
  	 	render 'users/show'
  	 else
  	 	# redirect_to new_session_path
  	 	render 'sessions/new'
  	end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :authenticate, only: [:new, :create :edit, :update, :destroy]


  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @user = current_user
    @post = @user.posts.create(post_params)
    redirect_to @post
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    # @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to @post
  end

  def destroy
    @post = Post.find(params[:id]).destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index

  end

# show login form
  def new
    # nothing
  end

  def create
    @user = User.find_by(session_params)
    if @user
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:alert] = 'Your email or passwaord are incorrect'
      redirect_to new_session_path
    end  
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
    session[:user_id] = nil
    redirect_to users_path
  end

   private

  def session_params
    params.require(:login).permit(:email, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :authenticate, only: [:edit, :update, :destroy]  

  # # shows all users
# / get local host: 3000/users
  def index
     @user = User.all

  end

# # / get local host: 3000/users/new
# # show form to make a new user
  def new
    @user = User.new
  end


# post to local host: 3000/users
# handles for submission and makes new user
  def create
    p params
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'account successfully created'
      redirect_to @user
    else
      flash[:alert] = 'your account did not get created'
      redirect_to new_user_path
    end
    redirect_to @user
  end

# / get local host: 3000/users/:id
# shows the user detail page
  def show
    @user = User.find(params[:id])
  end

# / get local host: 3000/users/:id/edit
# shows the form for editing the user
  def edit
    @user = User.find(params[:id])
  end

# / patch or put to  local host: 3000/users/:id
# handles updating the user info
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to @user
  end


# / delete request local host: 3000/users/:id
# destroys the user info
  def destroy
    @user = User.find(params[:id]).destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<%= link_to "christi", christi_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecondRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= link_to "User index", users_path %>
    <br

    <% if user_signed_in_?  %>
      <br>
    	<%= link_to "Post index", posts_path %>
      <br>
      <%= link_to "Post New", new_post_path %>
      <br>
      <%= link_to "Log Out", logout_path, method: :delete %>
    <% else %>
      <%= link_to "Login", new_session_path %>
      <br>
      <%= link_to "Create User", new_user_path %>
    <% end %>
    <%= yield %>

     
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>


<p>Edit Post</p>
	<%= form_with model: @post do |f| %>
	<%= f.label :Title %>
	<%= f.text_field :title, placeholder: 'title' %>
	<%= f.text_field :content, placeholder: 'content'%>
	<%= f.submit "Edit Post" %>
<% end %>

	<%= link_to "Destroy", @post, method: :delete %>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

New Posts
<% @posts.each do |post| %>
	<p><%= post.title %>
	<p><%= post.content %>

	<%= link_to "Post Show", post %>
	<%= link_to post.title, post %>
	<%= link_to "Edit Post", edit_post_path(post) %>
	<%= link_to "Destroy", post, method: :delete %>
		<%# link_to user.full_name, user %>
<% end %>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>



<p>Create a Post</p>
<%= form_with model: @post do |f| %>
<%= f.label :Title %>
	<%= f.text_field :title, placeholder: 'title' %>
	<%= f.text_field :content, placeholder: 'content'%>
			<input type="hidden" name="user_id" value="6">
	<%= f.submit "Create Post" %>
<% end %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>


<h1>Posts</h1>
<%= @post.title %>
<%= @post.content %>
<%= @post.created_at %>

	<%= link_to "Edit Post", edit_post_path(@post) %>
	<%= link_to "Destroy", @post, method: :delete %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

<%= form_with model: @user do |f| %>
	<%= f.text_field :first_name, placeholder: 'first_name' %>
	<%= f.text_field :last_name, placeholder: 'last_name' %>
	<%= f.text_field :email, placeholder: 'email' %>
	<%= f.password_field :password, placeholder: 'password'%>
	<%= f.submit "Update" %>
	
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<p>you just created



<% @user.each do |user| %>
	<p><%= user.first_name %>
	<p><%= user.last_name %>
	<p><%= user.email %>
	<p><%= user.password %>
	<%= link_to "User Show", user %>
		<%= link_to user.first_name, user %>
		<%= link_to "Edit User", edit_user_path(user) %>
			<%= link_to "Destroy", user, method: :delete %>
		<%# link_to user.full_name, user %>
<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
<%= form_with model: @user do |f| %>
<%= f.label :first_name %>
	<%= f.text_field :first_name, placeholder: 'first name' %>
	<%= f.text_field :last_name, placeholder: 'last name'%>
	<%= f.text_field :email, placeholder: 'email'%>
	<%= f.password_field :password, placeholder: 'password'%>
	<%= f.submit "Create User" %>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
selected user has an id <%= @user.id %> and a name of <%= @user.first_name %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>